### ISSUE TITLE
orthogonal projections and estimated normals

### ISSUE THREAD

**Issue by l1346792580123** [CyberAgentAILab/SuperNormal#11]
Thanks for opening source such great work! I found that the code uses a same way as idr to handle perspective projection. What modifications need to be made to adapt to orthogonal projection? In addition, have you tried using incorrect normal vectors to get the results? For example, using the normal map estimated by a monocular normal estimation model.

**Comment by xucao-42** [comment]
Our method is prone to inaccurate normal maps. You can check the result in Fig. 8 of [the paper.](https://openaccess.thecvf.com/content/CVPR2024/papers/Cao_SuperNormal_Neural_Surface_Reconstruction_via_Multi-View_Normal_Integration_CVPR_2024_paper.pdf)

To tailor our method to orthogonal projections, pls modify this line (and other parts related to computing rays in the camera and world space) https://github.com/CyberAgentAILab/SuperNormal/blob/7979c5f29dc3a02d7bb3570bb5cbd841c4ed23a8/models/dataset_loader.py#L165

**Comment by l1346792580123** [comment]
Thanks for your reply!
