### ISSUE TITLE
How is scal_mat calculated?

### ISSUE THREAD

**Issue by therealron** [CyberAgentAILab/SuperNormal#5]
Hi, great work! In the data, how is the scale_mat calculated? 
It is used to bring the points in the unit sphere to world coordinates so that we can project them into the camera using the world_mat, right?

If I am trying to use this method for my own data, and I have per-view normals(in world space) and the KRT's for each camera, how can I calculate the scale matrix from this information? Thanks!

**Comment by xucao-42** [comment]
Sorry for late reply, I was busy recently.

The scale_mat is simply a 3x3 diagnal matrix with identical values along the diagonal axis. To calculate the scale term, you can refer to [the code in my previous work](https://github.com/xucao-42/mvas/blob/main/code/utils/camera_normalization.py) and [an explanation in last section](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Cao_Multi-View_Azimuth_Stereo_CVPR_2023_supplemental.pdf). We will also release the data pre-processing scripts and raw data recently. 

Hope it helps!

**Comment by utopiar** [comment]
Hi, great work! When do you plan to release the data pre-processing scripts and raw data ？

**Comment by xucao-42** [comment]
> Hi, great work! When do you plan to release the data pre-processing scripts and raw data ？

Thank you for your interest. The raw data and scripts are now available [here](https://github.com/CyberAgentAILab/SuperNormal/tree/main/data_capture_and_preprocessing).
